/*************************************************************************//**
 *****************************************************************************
 * @file   sl.c
 * @brief  sl
 * @author Sweet
 * @date   2015
 *****************************************************************************
 *****************************************************************************/

#include "type.h"
#include "stdio.h"
#include "const.h"
#include "protect.h"
#include "string.h"
#include "fs.h"
#include "proc.h"
#include "tty.h"
#include "console.h"
#include "global.h"
#include "proto.h"

/*****************************************************************************
 *                                sl
 *****************************************************************************/


PUBLIC void sl(){

  int delay_time = 10000;
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange Kernal     xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("              *************              xx                                 \n");
  printf("                ************             xx                                 \n");
  printf("                  ****************       xx                                 \n");
  printf("                         *******                                            \n");
  printf("                           ***                                              \n");
  printf("                            *                                               \n");
  printf("                                                                            \n");
  printf(" ##   ##   ##  #######  ##        #####     #####       ##  ##     #######  \n");
  printf(" ##   ##   ##  ##       ##       ##    #   ##   ##     ###  ###    ##       \n");
  printf("  ##  ##  ##   #######  ##      ##        ##     ##   ##  ##  ##   #######  \n");
  printf("   ###  ###    ##       ##       ##    #   ##   ##   ##   ##   ##  ##       \n");
  printf("    ##  ##     #######  #######   #####     #####    ##   ##   ##  #######  \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);

  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");                      
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");                      
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");                      
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                          ##\n");
  printf("                                                                          ##\n");
  printf("                                                                          ##\n");
  printf("                                                                          ##\n");
  printf("                                                                          ##\n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");                      
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                    ####### \n");
  printf("                                                                    ##    ##\n");
  printf("                                                                    ######  \n");
  printf("                                                                    ##    ##\n");
  printf("                                                                    ####### \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("                                                                            \n");
  printf("                                                                            \n");                      
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                              #######   ####\n");
  printf("                                                              ##    ##    ##\n");
  printf("                                                              ######      ##\n");
  printf("                                                              ##    ##    ##\n");
  printf("                                                              #######   ####\n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("                                                                            \n");                      
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                        #######   ######  ##\n");
  printf("                                                        ##    ##    ##    ##\n");
  printf("                                                        ######      ##    ##\n");
  printf("                                                        ##    ##    ##    ##\n");
  printf("                                                        #######   ######  ##\n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                  #######   ######  ########\n");
  printf("                                                  ##    ##    ##    ##     #\n");
  printf("                                                  ######      ##    ########\n");
  printf("                                                  ##    ##    ##    ##  ##  \n");
  printf("                                                  #######   ######  ##    ##\n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                            #######   ######  ########   ###\n");
  printf("                                            ##    ##    ##    ##     ##  ## \n");
  printf("                                            ######      ##    ########   ## \n");
  printf("                                            ##    ##    ##    ##  ##     ## \n");
  printf("                                            #######   ######  ##    ###  ###\n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                      #######   ######  ########   #####    \n");
  printf("                                      ##    ##    ##    ##     ##  ##   ##  \n");
  printf("                                      ######      ##    ########   ##    ## \n");
  printf("                                      ##    ##    ##    ##  ##     ##   ##  \n");
  printf("                                      #######   ######  ##    ###  #####    \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("              *************              xx                             xx  \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                #######   ######  ########   #####          \n");
  printf("                                ##    ##    ##    ##     ##  ##   ##        \n");
  printf("                                ######      ##    ########   ##    ##  #####\n");
  printf("                                ##    ##    ##    ##  ##     ##   ##        \n");
  printf("                                #######   ######  ##    ###  #####          \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("              *************              xx                             xx  \n");
  printf("                ************             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                          #######   ######  ########   #####                \n");
  printf("                          ##    ##    ##    ##     ##  ##   ##             #\n");
  printf("                          ######      ##    ########   ##    ##  #######  ##\n");
  printf("                          ##    ##    ##    ##  ##     ##   ##             #\n");
  printf("                          #######   ######  ##    ###  #####                \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("              *************              xx                             xx  \n");
  printf("                ************             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("                  ****************                                          \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                    #######   ######  ########   #####                ######\n");
  printf("                    ##    ##    ##    ##     ##  ##   ##             ##    #\n");
  printf("                    ######      ##    ########   ##    ##  #######  ##      \n");
  printf("                    ##    ##    ##    ##  ##     ##   ##             ##    #\n");
  printf("                    #######   ######  ##    ###  #####                ######\n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("              *************              xx                             xx  \n");
  printf("                ************             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("                  ****************                                          \n");
  printf("                         *******                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("              #######   ######  ########   #####                ######      \n");
  printf("              ##    ##    ##    ##     ##  ##   ##             ##    ##   ##\n");
  printf("              ######      ##    ########   ##    ##  #######  ##      ##    \n");
  printf("              ##    ##    ##    ##  ##     ##   ##             ##    ##   # \n");
  printf("              #######   ######  ##    ###  #####                ######     #\n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("              *************              xx                             xx  \n");
  printf("                ************             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("                  ****************                                          \n");
  printf("                         *******                                            \n");
  printf("                           ***                                              \n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("        #######   ######  ########   #####                ######      ######\n");
  printf("        ##    ##    ##    ##     ##  ##   ##             ##    ##   ##      \n");
  printf("        ######      ##    ########   ##    ##  #######  ##      ##    ##### \n");
  printf("        ##    ##    ##    ##  ##     ##   ##             ##    ##   #      #\n");
  printf("        #######   ######  ##    ###  #####                ######     ###### \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time);
  clear();
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  printf("                                                                            \n");
  printf("                                                                            \n");
  printf("                            **************                                  \n");
  printf("                          **  **********                                    \n");
  printf("             ******     ***  *********                                      \n");
  printf("           ** @  ***  ***  ********      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("       ****       ****   *******         xx                             xx  \n");
  printf("            ********   *******           xx  Bird-OS                    xx  \n");                      
  printf("            *********  ****              xx  Based on Orange's Kernal   xx  \n");
  printf("             ******** ****               xx  version 1.0.0              xx  \n");
  printf("              *************              xx                             xx  \n");
  printf("                ************             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n");
  printf("                  ****************                                          \n");
  printf("                         *******                                            \n");
  printf("                           ***                                              \n");
  printf("                            *                                               \n");
  printf("                                                                            \n");
  printf("    #######   ######  ########   #####                ######      ######    \n");
  printf("    ##    ##    ##    ##     ##  ##   ##             ##    ##   ##      #   \n");
  printf("    ######      ##    ########   ##    ##  #######  ##      ##    #####     \n");
  printf("    ##    ##    ##    ##  ##     ##   ##             ##    ##   #      ##   \n");
  printf("    #######   ######  ##    ###  #####                ######     ######     \n");
  printf("                                                                            \n");
  printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n");
  milli_delay(delay_time+500000);
  
}
